### ISSUE TITLE
Feature Request - Starts Numbering from 00

### ISSUE THREAD

**Issue by inessashillo** [rodi01/RenameIt#102]
Hi! Thank you for the awesome plugin! It would be even more lovely if the numbering can start from 00 and the proceed to 10.

![image](https://user-images.githubusercontent.com/29578643/48779939-be5b7500-ece9-11e8-96e5-ad5309a92cf3.png)

Will be very much appreciated!

**Comment by rodi01** [comment]
You should be able to do this right now. Try this: `%NN`

The number of “n” will dictate the number of zeros.
