### ISSUE TITLE
Feature Request - Sort Artboards by Row or Column

### ISSUE THREAD

**Issue by inessashillo** [rodi01/RenameIt#103]
Hi again, I also thoght of a feature when the plugin can understand that I want to name it in row or column order, not by the position in the layer tab (I never maintain a correct order in there).

Thank you for your product anyway!

**Comment by rodi01** [comment]
This is a hard one. It’s requires a much bigger rewrite and rethinking of the plugin. I think it’s a great feature that I want to try to add in one day, thanks for suggesting it.
