### ISSUE TITLE
Rename it doesn't load for me.

### ISSUE THREAD

**Issue by redg1402** [rodi01/RenameIt#105]
I've installed rename it, but when am triggering it from the plugin section in sketch it doesn't make anything... i've installed it 3 times and still not working. Tried loading it from sketch runner shortcut but the same still happening. Even the settings are unreachable, doesn't work.

here my computer specs
![image](https://user-images.githubusercontent.com/46534905/50914581-e2dbef80-1404-11e9-852d-80389992c5fe.png)

Sketchapp Version 52.6
Rename it 3.9.6

**Comment by rodi01** [comment]
Can you try installing this version? https://www.dropbox.com/s/6gnm1gl512jsb8c/Rename-It.sketchplugin.zip?dl=1

Make sure you delete the old version.
