### ISSUE TITLE
4.0.0 Breaks styles

### ISSUE THREAD

**Issue by everydayslang** [rodi01/RenameIt#106]
<img width="504" alt="screen shot 2019-01-17 at 4 55 24 pm" src="https://user-images.githubusercontent.com/11896980/51351362-b5ccb400-1a78-11e9-9634-a1e2584da211.png">

**Comment by rodi01** [comment]
Huh! Did you try relaunching sketch? Which OS are you on?

**Comment by everydayslang** [comment]
I restarted and am pleasantly surprise by this new interface 😁
<img width="504" alt="screen shot 2019-01-17 at 7 00 54 pm" src="https://user-images.githubusercontent.com/11896980/51356859-3942d100-1a8a-11e9-95c8-fe687fa0fd2d.png">
 Thanks

**Comment by rodi01** [comment]
Perfect!
