### ISSUE TITLE
Missing Stylesheet?

### ISSUE THREAD

**Issue by sonburn** [rodi01/RenameIt#107]
The stylesheet appears to missing or not loading properly in the latest update (v4.0.0), and you can only type one value in the field (I assume it's failing due as it's trying to provide examples of the output results down below).

![image](https://user-images.githubusercontent.com/248364/51412440-364eeb80-1b31-11e9-855c-5ccebc7b005e.png)

**Comment by rodi01** [comment]
Looks like restarting sketch should fix this. Can you try?

**Comment by sonburn** [comment]
@rodi01 A restart did resolve the issue, apologies.

**Comment by rodi01** [comment]
No worries at all. I think I will have to add a modal to restart sketch but I hate to do that with the user. 😔
