### ISSUE TITLE
Feature request - Ascending order alpha sequence

### ISSUE THREAD

**Issue by chetTheJet** [rodi01/RenameIt#108]
Currently alpha sequence is in descending order

**Comment by rodi01** [comment]
Try this `%ar%`

**Comment by chetTheJet** [comment]
Thanks for the quick response Rodi01. Using that, the names on the artboards still appear in descending order and show dr%, cr%, br%, ar%. Using just %a shows lowercase descending alpha order. Any other suggestions?

**Comment by rodi01** [comment]
Do you have the latest version 4.0?

**Comment by chetTheJet** [comment]
No, I have the previous version because when I updated to the 4.0, the interface styling was all gone and the plugin wouldn't work correctly

**Comment by chetTheJet** [comment]
Thank you, it worked!

**Comment by rodi01** [comment]
Awesome!
