### ISSUE TITLE
Find and Replace crashes

### ISSUE THREAD

**Issue by polzav** [rodi01/RenameIt#114]
Find and Replace the screen crashes to white screen in any action.
Sketch 54.1, Plugin version 4.1.1
![image](https://user-images.githubusercontent.com/19476756/57602693-8599ab80-7568-11e9-8ee1-f4d70a30affc.png)

**Comment by gabsmaster** [comment]
Same, using sketch 54.1 as well and just updated the plugin

**Comment by cpshanley** [comment]
Confirmed.

**Comment by mindquest** [comment]
where did you get the rollback? it's happing to me as well

**Comment by rodi01** [comment]
@mindquest I just rolled it back, can you try to update it.

**Comment by cpshanley** [comment]
> where did you get the rollback? it's happing to me as well

Here. Click on Code and then Releases.

Download 4.1.0

**Comment by mindquest** [comment]
Thanks I think its been rolled back officially works now

**Comment by cpshanley** [comment]
Yes, 4.1.2 is working fine.

Kudos for fixing that inside a day.

**Comment by newbit77** [comment]
Same, using sketch 54.1 as well and just updated the plugin

**Comment by Raghav789** [comment]
same here, using sketch v53, just updated still not working

**Comment by rodi01** [comment]
@newbit77 @Raghav789  Phew! I'm glad it worked.
