### ISSUE TITLE
Rename it disappears after typing in it 

### ISSUE THREAD

**Issue by mindquest** [rodi01/RenameIt#115]
I'm using sketch 54.1 .  The text fields disappear when I start to type in them so I can't do any layer updates at all.

**Comment by vedranzidanik** [comment]
I'm having the same issue.

**Comment by mindquest** [comment]
I tried restarting still not working....still disappears after typing in text field.  Using macOS High Sierra 10.13.6 (17G6030)

**Comment by mnizinski79** [comment]
Same issue - only on find and replace though. 

![image](https://user-images.githubusercontent.com/7937959/57627208-8bda5880-7565-11e9-88ae-945435f9b5e0.png)

**Comment by mindquest** [comment]
I see it on another computer that has not updated Runner yet.  Did you guys update runner?  Just trying to think why it's no longer working.

**Comment by mindquest** [comment]
no, I reverted runner and it's still not working!!

**Comment by mnizinski79** [comment]
Runner has been updated. I think it was updated on Friday.

**Comment by mindquest** [comment]
![Screen Shot 2019-05-13 at 10 39 49 AM](https://user-images.githubusercontent.com/26074456/57630371-7e27d180-756b-11e9-8912-0653fe61ea85.png)

**Comment by vedranzidanik** [comment]
I don't even use Runner, so I think it has nothing to do with it. I'm seeing this issue with last two versions of the plugin. On Find/Replace.

**Comment by JunkerDominik** [comment]
same problem here!

**Comment by rodi01** [comment]
I'm working on a quick fix for now. I will up date soon. My apologies.

**Comment by rodi01** [comment]
I just rolled it back, can you try to updated it. You might have to restart Sketch.

**Comment by JunkerDominik** [comment]
Thank you very much!

**Comment by mindquest** [comment]
Works!  Thanks so much for handling this quickly!
