### ISSUE TITLE
Rename Artboards to Title Case doesn't work on symbols with slashes in the name

### ISSUE THREAD

**Issue by cheics-d2l** [rodi01/RenameIt#116]
Lowercase works as expected:
![image](https://user-images.githubusercontent.com/8430763/57638691-4e34fa00-757c-11e9-86a0-1744a04595ba.png)

Title Case isn't able to process the symbol name:
![image](https://user-images.githubusercontent.com/8430763/57638827-90f6d200-757c-11e9-80a8-2442cd751274.png)

**Comment by cheics-d2l** [comment]
The preview still shows all UPPERCASE instead of Title Case - but thank you so much for the quick fix, saving me a lot of time.

![image](https://user-images.githubusercontent.com/8430763/57719456-ce776000-764d-11e9-80c4-00cb28f33109.png)

**Comment by rodi01** [comment]
@cheics-d2l try restarting Sketch. Hopefully it will fix the preview

**Comment by cheics-d2l** [comment]
Restarting Sketch fixed the preview. Thanks again!
