### ISSUE TITLE
Numbers >= 10

### ISSUE THREAD

**Issue by tbnv** [rodi01/RenameIt#12]
At this time, it looks like %N doesn't go above 9.
Instead of numbering 9, 10, 11, 12 it returns 9, 0, 1, 2.

Edit: I know that using %NN includes leading zeros etc. but I think that the above is still true and should not go back to 0 after 9.

**Comment by baronetto** [comment]
Is there a solution to this yet? Any workarounds?

**Comment by rodi01** [comment]
The workaround is to use the %NN. I'm working on a fix
