### ISSUE TITLE
Sketch 52.2 not compatible plugin

### ISSUE THREAD

**Issue by dwinurhadia** [rodi01/RenameIt#122]
I was update to latest sketch and compatible with version 4.2.1

**Comment by rodi01** [comment]
What version of Sketch are you running right now? The latest 55.2?

**Comment by jannikolaas** [comment]
Same issue here. Yes Sketch 55.2.
<img width="474" alt="pluginissue" src="https://user-images.githubusercontent.com/1139110/59367543-9b9fb500-8d3c-11e9-98fe-a1fda8f38d06.png">

**Comment by rodi01** [comment]
Just to let you guys know, I'm currently looking at this issue. For now, you can manually enable it on the plugin manager and it work just fine. I will post an update as soon as I find the issue.
Thanks for understanding it.

**Comment by rodi01** [comment]
Should be fixed now, please update the plugin

**Comment by chsWeb** [comment]
JFYI, RenameIt does work when manually reenabled, but I do not see any updates available for the plugin via Sketch.

**Comment by rodi01** [comment]
@chsWeb have you tried restarting Sketch?
