### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by Kamui0001** [rodi01/RenameIt#129]
Hello,

I have a small issue with the plugin. I have sketch 56.3 on Mac OS 15.1 (Catalina).
As of the beginning of this week, impossible to launch the plugin. I click on the find and replace function. I see the rainbow wheel of Mac, meaning "I do something" but finally nothing appears on the screen.

Do you have an idea of the issue?

Thank you for your help.
Kind regards.
Jon

**Comment by rodi01** [comment]
Unfortunately, this is an issue with Sketch and Catalina, the only way to fix this is to update Sketch. 

I asked the same thing and one of the sketch devs mentioned upgrading to the latest Sketch is the only solution. Here is what I posted https://github.com/skpm/sketch-module-web-view/issues/133
