### ISSUE TITLE
Sketch 63

### ISSUE THREAD

**Issue by MotsyRobotsy1984** [rodi01/RenameIt#130]
Hi guys,

Rename It doesn't appear to work with Sketch 63, is that correct? Will you be releasing an update to make it compatible any time soon?

**Comment by rodi01** [comment]
@MotsyRobotsy1984 I just tried on the 63.1 version released today and it's working. Can you try on the new version?

**Comment by MotsyRobotsy1984** [comment]
Hey buddy, thanks for the message. Let me try now, as I hadn't seen a .1 version of Sketch 63 had been made available.

**Comment by jonnydevv** [comment]
Hello,
Plugin is incompatible with Version 64 (93537)

**Comment by rodi01** [comment]
@jonnydevv Is it showing as incompatible in the plugin list?

**Comment by jonnydevv** [comment]
Upon install it shows the message "This plugin is incompatible with Sketch 64. The plugin “Rename-It” is incompatible with Sketch 64. Do you want to install the Plugin?".
So i didn't installed.

**Comment by rodi01** [comment]
@jonnydevv I'm currently using it Sketch 64 and it's working fine, it's safe to install. I'll see if I can find the issue, thanks for letting me know
