### ISSUE TITLE
Feature Request: Rename folder based on child text

### ISSUE THREAD

**Issue by JordanTranchina** [rodi01/RenameIt#133]
Example: I have a folder with two text layers. 
I would like a way to rename the folder to be the same as the value entered in the first child text layer. This would be amazing for lists!

**Comment by JordanTranchina** [comment]
<img width="988" alt="Screen Shot 2020-04-21 at 10 56 01 AM" src="https://user-images.githubusercontent.com/41443492/79906312-8f1ccc00-83e5-11ea-846b-5c5b33a2d324.png">
In the attached. It'd be great to have a feature in which I can rename "Rename This Folder" with "Assets" (the child text value)

**Comment by rodi01** [comment]
This is interesting, I've never got a request for this feature. I got tons of requests for the parent naming which I have in the plugin. 

I'll take a look to see what's involved to make this.

**Comment by JordanTranchina** [comment]
Whoops attached the wrong screenshot but let me know if you have any clarifying questions :) THANK YOU!

**Comment by rodi01** [comment]
Good News! This wasn't too hard to add in, I'll be releasing a new version of it today. 

Thanks for the suggestion

**Comment by JordanTranchina** [comment]
Hey @rodi01 thanks so much for making this! One small bug fix: It appears that this will use the last text layer on the layer list and use it as the folder name. Is there any way to make it take the first text layer?


![Screen Shot 2020-04-23 at 1 08 51 PM](https://user-images.githubusercontent.com/41443492/80128393-9833a780-8563-11ea-91fc-9c555eeda489.png)

Current Experience: Folder is renamed to "1,000,000"
Desired Experience: Folder is renamed to "Assets"


Thanks for all that you've already done! Great app :D

**Comment by rodi01** [comment]
good catch looks like a easy fix

**Comment by rodi01** [comment]
Pushed a fix

**Comment by JordanTranchina** [comment]
Awesome, thanks! Let me know whenever you push it to master and I'll test it out on Sketch. Haven't seen anything come through the pipes yet but may just be slow to update?

**Comment by rodi01** [comment]
It should be up, you might need to restart Sketch to get the notification

**Comment by JordanTranchina** [comment]
Verified complete and functional. Thanks so much for the quick turnaround!

Jordan Tranchina
Senior UX Designer | EY Design Studio | New York, NY
Website | LinkedIn | Schedule Call
