### ISSUE TITLE
Find and Replace swaps artboard names

### ISSUE THREAD

**Issue by braddee** [rodi01/RenameIt#136]
Have three artboards with a size suffix and type suffix.  Examples:  "...XL_Dog", "...Med_Dog", "...Small_Dog".  When I run a Find and Replace for "Dog" and replace with "Cat", the "...XL_Dog" artboard becomes "...Small_Cat" and the "...Small_Dog" board becomes "...XL_Cat".  The Med artboard seems to be working correctly.

**Comment by rodi01** [comment]
Can you check that you have the latest update 4.5.2

**Comment by braddee** [comment]
Yes, just got the prompt for the update.  Everything is working as expected!  Thanks so much.

P.S. This plugin is by far my favorite.  Great work!

**Comment by rodi01** [comment]
Awesome!
