### ISSUE TITLE
%N not working

### ISSUE THREAD

**Issue by JayHoltslander** [rodi01/RenameIt#14]
Plugin doesn't seem to work with Sketch 3.2.2
Watched the demo video 3 times. Read the instructions. Still get ten layers all named "Item %N" after running the plugin.

**Comment by rodi01** [comment]
@JayHoltslander I just checked on version 3.3.2 (12043), It works fine. The code was re-factored not too long ago to work on 3.3, I'm not sure if it will work on 3.2.x
