### ISSUE TITLE
Using Rename It 4.5.3 on version Sketch 70.2 (109071) for Apple Silicon crashes Sketch

### ISSUE THREAD

**Issue by lucasstinis** [rodi01/RenameIt#145]
As the title says, using Rename it 4.5.3 (any feature) on version Sketch 70.2 (109071) for Apple Silicon crashes Sketch each and every time. I'm running Big Sur 11.0.1 on a Mac Mini (M1 - 16 GB). I tried removing and then reinstalling it, which did not help.

**Comment by lucasstinis** [comment]
FYI, I'm using 70.3 now and it still crashes any time I try to run an action through the plugin.

**Comment by rodi01** [comment]
First of all, sorry for the inconvenience.

I did find a forum post about this issue on the plugin dev forum. Look like it's happening with more plugins and it might be an issue on the sketch side.  
https://sketchplugins.com/d/2261-plugin-crashes-sketch-with-arm-architecture

One note, I no longer use Sketch as my daily design tool, and I can't justify paying for the license to maintain this project. I hope it's a quick fix that I can just re-compile the project for ARM.

**Comment by phildziedzic** [comment]
Thanks for building and maintaining this, Rodrigo!

I'm also using an M1 mac and it's crashing. Any idea when you'd be able to re-compile for ARM to see if that does the trick?

**Comment by phildziedzic** [comment]
Side note for @lucasstinis: you can run Sketch using Rosetta, which allows the plugin to work!

Open inspector on the application (command + i) and check "open using Rosetta"
<img width="259" alt="Screen Shot 2021-01-14 at 17 10 42" src="https://user-images.githubusercontent.com/996942/104660221-c7f38400-568b-11eb-8881-befb5ea398c7.png">

Can't speak to the long-term performance, but it's ok for now!

**Comment by lucasstinis** [comment]
Thanks @phildziedzic and @rodi01! I will give running it under Rosetta 2 a try, but since performance isn't that good on the native M1 version, I'm afraid of seeing what running it that way will do, haha...

**Comment by ivancucer** [comment]
I see that the whole sketch community is dying. And literally, everyone moves to Figma. Unfortunately, I have to use Sketch just because there are a bunch of files I need to use on my current project...

**Comment by bomberstudios** [comment]
FYI, we’ve fixed this issue on Sketch 70.5, which we’ll release next week. Apologies for the inconvenience and thanks everyone for your patience 🧡

**Comment by lucasstinis** [comment]
> FYI, we’ve fixed this issue on Sketch 70.5, which we’ll release next week. Apologies for the inconvenience and thanks everyone for your patience 🧡

Thanks for doing this! I appreciate all the hard work you put in to this and am just glad it can be used again. Just tested it on my M1 running Big Sur 11.2.1, using Sketch 70.5, and it's working perfectly again.
