### ISSUE TITLE
Sometimes it fails to work

### ISSUE THREAD

**Issue by badyqb** [rodi01/RenameIt#16]
Hi, I found this plugin sometimes work but sometimes it fails to work.
I'm not sure if this happen because of sketch 4.3. It works fine in 3.3

**Comment by rodi01** [comment]
@badyqb It seems to be related to the latest Sketch. I saw the same issue with my plugin and many others but Sketch doesn't generate any error message. I just tried on the latest beta (3.4.1) and it's working fine, looks like they are working on an update soon.
