### ISSUE TITLE
Not an issues, a suggestion

### ISSUE THREAD

**Issue by julienpecorino** [rodi01/RenameIt#17]
Hello,
Thanks for this great plug in its amazing,
I would like to know if you could add an option to delete some characters in layer / artboard names.
I have more than 200 artboards in the app I'm currently designing and the artboard names are this:
onboarding_0056__A23_state_1

I would like to delete the "_0056__" in thoses artboard names

I tried to add a function to your plugin but I don't have enough skills to fully understand the code,
the regex I was trying to use was this: (?<=_)(.*)(?=A)
(delete everything between the first _ and the A)

If you could add a feature in your plugin it would be awesome.

Thanks

**Comment by rodi01** [comment]
That's a good idea, @julienpecorino! I will tag as a feature request, hopefully it isn't too hard to do.

**Comment by rodi01** [comment]
This can be achieved with the find & replace feature
