### ISSUE TITLE
Reverse %N order for the selected layers

### ISSUE THREAD

**Issue by ivancucer** [rodi01/RenameIt#18]
Hello,

It'd be great if you add the ability to choose the type of order:
1. From first to last
2. From last to first

Now it is possible to rename from the first to the last layer.

Thank you!

Best,
Ivan

**Comment by rodi01** [comment]
Hi Ivan,

Try using lowercase %n, it reverses the order. Is that what you mean?

Thanks

**Comment by ivancucer** [comment]
Hey,

Thank you for your reply. Oh sorry my bad, I didn't read the description properly :)

Ivan
