### ISSUE TITLE
Interval for %N

### ISSUE THREAD

**Issue by ivancucer** [rodi01/RenameIt#19]
Hello,

It'd be great if you add the ability to choose an interval eg. `20-29`

Now it is possible to rename only from the starting number.

Thank you!

Best,
Ivan

**Comment by rodi01** [comment]
Hi Ivan, 
I'm trying to figure it out how would this work. Can you give me an example how it would apply?

Do you mean only 9 layers will be renamed if chosen 20-29 interval?

Thanks

**Comment by ivancucer** [comment]
Hey,

Thank you for your reply. Yes exactly :) 

![monosnap 2015-11-09 21-18-25](https://cloud.githubusercontent.com/assets/2349195/11045415/9a0d7b4c-8727-11e5-948c-2d86c71aeb17.jpg)

Best,
Ivan
