### ISSUE TITLE
Rename subfolders and layers inside a folder.

### ISSUE THREAD

**Issue by dantasjadson** [rodi01/RenameIt#20]
Amazing work, Rodrigo! I have installed it but, for example, if I have five folders and, inside, some layers and I want update all these folders and layers' name, I can't to do it. Is there some way to do it?

Thanks @rodi01 !

**Comment by heckmac** [comment]
+1

I'd also love to be able to rename a subfolder.

Thanks!

**Comment by rodi01** [comment]
This is a limitation with sketch where the user can't select subfolder and its parent.
