### ISSUE TITLE
Option to reverse %n naming based on Sketch's logic

### ISSUE THREAD

**Issue by benstronaut** [rodi01/RenameIt#21]
When duplicating layers, they move up in the sketch layer tree so to speak.
User must then move the layers in reverse order so that the rename plug will properly order with %N.
Could we have an option to reverse that naming so the top most layer isn't #1 it's actually the last number in the list?

**Comment by benstronaut** [comment]
Step 1: Duplicating an artboard 7 times moves the layers upwards on the layers list.

<img width="1212" alt="screen shot 2016-04-29 at 3 54 20 pm" src="https://cloud.githubusercontent.com/assets/13004940/14931778/f4205f96-0e22-11e6-8e2a-eb48c7ad57df.png">

Step 2: Then when using %n re-name it, the artboards are reversed.

<img width="1208" alt="screen shot 2016-04-29 at 3 54 55 pm" src="https://cloud.githubusercontent.com/assets/13004940/14931777/f41ff114-0e22-11e6-8fba-d7fb7fc5ab88.png">

**Comment by benstronaut** [comment]
Desired result: 
<img width="1205" alt="screen shot 2016-04-29 at 3 58 25 pm" src="https://cloud.githubusercontent.com/assets/13004940/14931811/3cf909d4-0e23-11e6-9a94-39e2ca1e8c4a.png">

**Comment by MAJ3STIC** [comment]
Has this been solved?

**Comment by benstronaut** [comment]
Not to my knowledge!

**Comment by rodi01** [comment]
Lowercase %n rename the layers ascending order.
Uppercase %N rename the layers in descending order.
