### ISSUE TITLE
Feature request: rename symbol instances to actual symbol name

### ISSUE THREAD

**Issue by leannegunn** [rodi01/RenameIt#22]
It would be great if you could rename symbol instances to the actual symbol name. For example, if you have 2 symbols called Button Default and Button Pressed, and you have an instance of "Button Default" that you then replace with Button Pressed, the name of the symbol instance is still "Button Default," when it's actually now an instance of Button Pressed.

**Comment by leannegunn** [comment]
UPDATE: I found [this plugin](https://github.com/exevil/sketch-rename-instances) which does what I am asking, something to consider blending in if you're up for it-- thanks :)

**Comment by rodi01** [comment]
Interesting idea @leannegunn. I might include it in the next version. Thanks for the suggestion.
