### ISSUE TITLE
Feature request: use of tab button

### ISSUE THREAD

**Issue by lysykrzys** [rodi01/RenameIt#26]
Can you add a tab button option, so we could quickly change between input boxes in Rename window?

**Comment by PDXIII** [comment]
I vote for that! And additionally could you please put the first input field in focus, so that your user can start typing immediately.

**Comment by rodi01** [comment]
This should work, make sure you have the latest version installed.

**Comment by lysykrzys** [comment]
It works. Thank you !!

**Comment by joshuarrr** [comment]
I somehow had two versions of Rename It installed, and the old one was taking precedence. I deleted it and now see these features. Just in case anyone else is similarly perplexed.

**Comment by rodi01** [comment]
@joshuarrr huh! Which version are you running?

**Comment by joshuarrr** [comment]
I'm up to date on 3.8.7 now; version 2 was stuck in service.
