### ISSUE TITLE
Enhancement: Have ability to add 0 for %N to aid in sorting exported assets

### ISSUE THREAD

**Issue by c5inco** [rodi01/RenameIt#27]
Hello, I love the plugin!  One thing that would be nice is if you could specify adding a "0" when using %N for the cases of selections that are between 1 and 9.  This is because when sorting exported assets on the filesystem, "11-layername.png" with come before "2-layername.png".

**Comment by blaineb** [comment]
You can do this by adding %NN into the input.  Hope t
![00 index](https://cloud.githubusercontent.com/assets/1864893/23963759/95c3fe32-096f-11e7-8621-db550ebd5f64.gif)

**Comment by c5inco** [comment]
Oh awesome - thanks for the tip!
