### ISSUE TITLE
New feature edit part words|folder

### ISSUE THREAD

**Issue by Prestapro** [rodi01/RenameIt#31]
Hello,
It great plugin seriously
I have strange text export from illustrator
_xA0_Image
I want drop all part phrases in all layers, but i don`t how make it
Screen:
http://prntscr.com/f573uc

Any idea?
Maybe it help a lot of people.

Regards,
Alexandr

**Comment by rodi01** [comment]
You can use the Find & Replace Layers Name and leave the replace field empty. 
Like this: 
![Find Replace](https://d2ppvlu71ri8gs.cloudfront.net/items/2q3r3D2L1h2W3H0C0H2x/Screen%20Shot%202017-05-12%20at%208.34.50%20PM.png)
