### ISSUE TITLE
Variable Parent Name

### ISSUE THREAD

**Issue by Charlotte923** [rodi01/RenameIt#34]
Hi,

First of all, I love this plugin.

I would like to ask if it's possible to have a parent variable, just like the use of the '*', but then something like '*P' which will use the name of the folder that your elements are in. This would be super useful.

Thanks!

**Comment by rodi01** [comment]
@Charlotte923 That's an interesting feature. I will see what it takes to make it happen. 

Thanks!

**Comment by rodi01** [comment]
Added this on the latest release #59 

The key is %o for the parent
