### ISSUE TITLE
Adjustment on pop-up modal

### ISSUE THREAD

**Issue by Albertovitullo** [rodi01/RenameIt#38]
Hi man, I use your plugin on a daily basis, and I find it really useful 👍 
There is one detail which really annoys me though, and therefore I decided to write you about it. It's a very minor thing, but it would really speed up my workflow.

Is it possible to have the first of the input fields already active when launching the plugin? Basically when I click "rename it" I would love the modal to appear blinking, so I can start typing directly, without having to grab my mouse and point into the input field to activate it?!

it's really minor, and geeky, but I'd love that!

thanks!

**Comment by rodi01** [comment]
That issue was fixed. Have you tried updating the plugin?

Let me know if that works.

**Comment by Albertovitullo** [comment]
Yes - just downloaded and installed again. Doesn't work :)

**Comment by rodi01** [comment]
Which version of sketch are you on? I can't reproduce it on my end.
