### ISSUE TITLE
Feature request: default to last used values

### ISSUE THREAD

**Issue by alampros** [rodi01/RenameIt#39]
It would be nice to have a starting point sometimes. Either the current layer name or the last used value would be very helpful (pre-selected so you can just start typing to clear it out).

Thanks!

**Comment by rodi01** [comment]
@alampros That's a great idea! I'm about to release a big update and I think this would be a good thing to add to the next version. What do you think of a auto-complete with recent results?

**Comment by Mco-Design** [comment]
What about having something similar to Renamy plugin on Photoshop? See link below:
https://cdn.dribbble.com/users/5911/screenshots/1188239/renamy-plugin.gif

**Comment by alampros** [comment]
That's pretty awesome! I think that would work great, but probably best as an input component with a dropdown. However, I don't know anything about sketch plugin UI development.

![i have no idea what im doing](https://cdn-images-1.medium.com/max/455/1*snTXFElFuQLSFDnvZKJ6IA.png)

**Comment by rodi01** [comment]
Added history to the last update
