### ISSUE TITLE
Change Case

### ISSUE THREAD

**Issue by pelegred** [rodi01/RenameIt#40]
Is here where you request a feature? sorry if not... 😖 

how about changing case of [original name] by entering something like this

```
example name - My symbol

* - keeps current name "My symbol"
*lc - for lower case "my symbol"
*uc - for upper case "MY SYMBOL"
*tc - for title case "My Symbol"
```

love this plugin ❤️

**Comment by rodi01** [comment]
Great idea! I have to figure out how to escape the letters in case someone wants to actually write lc after the name.

**Comment by johanneslamers** [comment]
This would be great!

**Comment by johanneslamers** [comment]
Just add one more rule:
```
*sc - for sentence case "My symbol"
```

**Comment by rodi01** [comment]
@johanneslamers any ideas on how to escape *sc for users that want to actually use “sc” after the *
The reason why I haven’t implemented this feature is because I can’t find a away to escape it.

**Comment by rodi01** [comment]
Finally added this feature #59 
The only compromise is that I had to change * to %*

```
%* - Layer name (original name)

%*u% - LAYER NAME (uppercase)

%*l% - layer name (lowercase)

%*t% - Layer Name (title case)

%*uf% - Layer name (uppercase first letter)

%*c% - layerName (Camel Case)
```

**Comment by zachj0hnston** [comment]
Thanks @rodi01! This is going to save us a lot of time :)
