### ISSUE TITLE
v2.0.7 download is missing

### ISSUE THREAD

**Issue by chrismessina** [rodi01/RenameIt#42]
I noticed that Sketch is reporting that v2.0.7 should be available, but tapping "update" doesn't do anything.

![preferences](https://user-images.githubusercontent.com/22610/28143945-605653ec-671d-11e7-8c62-64fa5b5ba46d.png)

It seems that the problem is that the 2.0.7 binary is missing:

https://github.com/rodi01/RenameIt/blob/master/RenameIt.zip?raw=true

...or at least that the file referenced in appcast.xml is a 404.

**Comment by rodi01** [comment]
@chrismessina Thanks! It should be fixed.
