### ISSUE TITLE
The shortcut `⌃⇧R` is in conflict with the default "Run previous plugin"

### ISSUE THREAD

**Issue by lanceplaine** [rodi01/RenameIt#43]
This shortcut overwrite the "Run previous plugin" in Sketch.
It would be great if you can use another keyboard shortcut. 

<kbd>⌃</kbd>+<kbd>⇧</kbd>+<kbd>R</kbd>

<img width="375" alt="screen shot 2017-07-17 at 1 28 42 pm" src="https://user-images.githubusercontent.com/5476205/28266199-e9089cfc-6af3-11e7-9e9a-2fb2ea1eab38.png">

Thanks!

**Comment by timurnurutdinov** [comment]
+1 here. "Rename selected Artboard" should be the first item in my opinion because plugin is not about it

**Comment by rodi01** [comment]
@timurnurutdinov @lanceplaine sorry about that. I'm going to remove the shortcut for now. 
FYI @JBLatenight

**Comment by timurnurutdinov** [comment]
Thanks for such a quick fix!

**Comment by lanceplaine** [comment]
Thanks :)
