### ISSUE TITLE
Feature request: Leading 0(s)

### ISSUE THREAD

**Issue by erindelaney** [rodi01/RenameIt#44]
Thank for you for this awesome plugin, it has saved me so much time!

If possible, it'd be great to be able to enter a leading 0 in the "Starts Number Sequence From:" field. For example, I frequently rename artboards with numbers for sorting purposes, but sequence 1 - 12 sorts as: 1, 11, 12, 2, 3, 4 etc. It'd be nice to be able to create a number sequence from 01 - 12.

**Comment by rodi01** [comment]
@erindelaney it's actually possible right now. The number of "N" dictates the sequence. In your case, try %NN or %nn and see if it works.

**Comment by erindelaney** [comment]
Oh fantastic, thank you so much! Thanks again for such a great plugin :)
