### ISSUE TITLE
⌃ + ⌘ + R shortcut doesn't work

### ISSUE THREAD

**Issue by ivancucer** [rodi01/RenameIt#45]
v2.0.8
Sketch 45.2
MacOS 10.12.5

**Comment by rodi01** [comment]
@ivancucer There must be another plugin overwriting the shortcut. I just tried it and it works fine on my end.
If there is another plugin overwriting the shortcut, there isn't much I can do. I hope Sketch will one day let the users manage shortcuts.

**Comment by ivancucer** [comment]
![untitled 2017-07-28 22-39-07](https://user-images.githubusercontent.com/2349195/28735512-d0c9f62c-73e5-11e7-89aa-7104406f19ad.jpg)

**Comment by ivancucer** [comment]
Hmm... I'm sorry. TopTracker.app uses `⌃ + ⌘ + R` shortcut 🤦‍♂️

**Comment by rodi01** [comment]
@ivancucer Another thing you can do is change the shortcut on the keyboard settings in the Mac System Preference.
![screen shot 2017-07-28 at 2 06 40 pm](https://user-images.githubusercontent.com/52461/28736325-30773a82-739e-11e7-85f5-acbe45de9934.png)
