### ISSUE TITLE
why i can't Rename Selected Artboard

### ISSUE THREAD

**Issue by olafchou** [rodi01/RenameIt#47]
<img width="421" alt="2017-08-08 11 41 10" src="https://user-images.githubusercontent.com/19890798/29055338-822e63d0-7c2e-11e7-8156-45db9feb7f77.png">

i selected several artboards ,but failed to rename it ,could you have a look at it ?it maybe a bug

**Comment by rodi01** [comment]
@olafchou It's a bug, it will be fixed on the next release. The workaround for now is to select the artboard and use the "Rename Selected Layers" feature instead, it should work.

**Comment by rodi01** [comment]
This is fixed on the latest release. Make sure to update your plugin.
