### ISSUE TITLE
the sequence is not right ?

### ISSUE THREAD

**Issue by olafchou** [rodi01/RenameIt#49]
<img width="820" alt="2017-09-05 15 38 43" src="https://user-images.githubusercontent.com/19890798/30050267-6a69c1bc-9250-11e7-894a-3d8143e1521d.png">

why the sequence is not right ？？

**Comment by olafchou** [comment]
![Uploading 屏幕快照 2017-09-05 15.42.28.png…]()
<img width="677" alt="2017-09-05 15 42 37" src="https://user-images.githubusercontent.com/19890798/30051429-8d4c7932-9254-11e7-96f0-79c61263585b.png">

**Comment by rodi01** [comment]
@olafchou The plugin rename according to the order of the layers/artboards and not to the position on the canvas. Order them first on the layer list and try again. 
I hope it helps.

**Comment by c5inco** [comment]
Ah that seems to be the issue.  It would be nice to order it based on X/Y.  Maybe that is another plugin that someone can make: the ability to reorder artboards based on X/Y.

**Comment by irfanrosandi** [comment]
yeah, i am looking for that plugin too that can order artboarts based on X/Y.

**Comment by rodi01** [comment]
This plugin "Automate" might help you sorting the artboards https://github.com/Ashung/Automate-Sketch
