### ISSUE TITLE
Start with 01

### ISSUE THREAD

**Issue by eaugustine** [rodi01/RenameIt#50]
Love this plugin! I wondered if you could add the ability to place a zero before the number when sorting by a number sequence. So the numbers could go "01, 02, 03,...10, 11, 12..."

**Comment by rodi01** [comment]
You can do that right now. Just add more “N” for the number of zeros. Ex. %nn or %NN

Rodrigo Soares
Follow me on Twitter | Instagram

**Comment by eaugustine** [comment]
Oh, wonderful! Thank you!
