### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Arroyodorado** [rodi01/RenameIt#51]
How about adding "%P" for the page name containing the artboard or layer? Would be useful sometimes.

Thanks for your work though, really like concept of this plugin.

**Comment by Arroyodorado** [comment]
Ok, I played around a bit with your code and added it myself. Is there an easy way to let you know the code changes? I'm not so familiar with the process of pull requests...

8-)

**Comment by rodi01** [comment]
Thanks a bunch! If you created a branch and pushed the code I can take a look if you post the commit hash here.

**Comment by rodi01** [comment]
@Arroyodorado I ended up coding that in, will be available on the next update. Thanks for the suggestion

**Comment by rodi01** [comment]
@Arroyodorado I ended up coding that in, will be available on the next update. Thanks for the suggestion

**Comment by Arroyodorado** [comment]
Oh, wow, cool! I was on the road over the weekend and didn’t have the time.

Anyway, thanks for your efforts and have a nice week.

8-)
