### ISSUE TITLE
Versions after v3.0.2 aren't installing

### ISSUE THREAD

**Issue by oeed** [rodi01/RenameIt#58]
For whatever reason, I can't seem to install any of the newer versions. I'll double click the .sketchplugin file but nothing happens. Likewise with Sketch Runner, it downloads it but it doesn't actually install. Only using v3.0.2 seems to work (i.e. bring up the 'Plugin has been installed' alert window).

I'm fine with v3.0.2, just though I'd let you know 😉

**Comment by rodi01** [comment]
Thanks, I will take a look.

**Comment by rodi01** [comment]
@oeed Are you able to update it from the Sketch plugins dialog?

**Comment by rodi01** [comment]
This should be fixed. Thanks for letting me know.
