### ISSUE TITLE
Feature request - individual selection

### ISSUE THREAD

**Issue by mischugo** [rodi01/RenameIt#67]
Hi,
How about replacing only one particular string of the selected layers / artboards ?
(replacing "-" or "dolor")
For example:
Lorem ipsum - dolor site
Lorem panemus - dolor site
Lorem - dolor sit

Thanks 

Maik

**Comment by rodi01** [comment]
@mischugo I don't know if I understand this correctly. Wouldn't the "Find & Replace Layers Names" feature work for this?

**Comment by mischugo** [comment]
I am so sorry, yes this works fine for me

Thanks

**Comment by rodi01** [comment]
No worries. Cheers!
