### ISSUE TITLE
Rename it only renames the layers on the layer panel, not the text on the artnboard

### ISSUE THREAD

**Issue by mkabelis** [rodi01/RenameIt#69]
Select: layers you want to rename
Select: Find and replace layers names
Find: "pix" 
Replace: "px"

Selected radio "selected layers"

Rename it ONLY changes the layers name from "pic" to "px" in the layer panel, text fields in artboard remain as "pix" - not renamed.

Rename it  used to change both.

**Comment by rodi01** [comment]
@mkabelis The plugin has never changed the actual content of a layer, it only changes the layer's name. This is something that I'm considering for future updates. 

If you are looking to find and replace text, take a look on this plugin: https://github.com/thierryc/Sketch-Find-And-Replace

Cheers

**Comment by mkabelis** [comment]
Ha, you are absolutely right,
Thank you for taking the time to reply.
My apologies, I got the two plugs confused!

**Comment by rodi01** [comment]
No problem. Let me know if you have any other questions.
