### ISSUE TITLE
Replace shortcut

### ISSUE THREAD

**Issue by Nicolas-th** [rodi01/RenameIt#70]
Hi, is it possible to replace to shortcut that runs the plugin? I'm using a plugin that already uses control + cmd + R as a shortcut so I can't use RenameIt with shortcuts..

**Comment by rodi01** [comment]
I use a plugin called Monster to manage all the plugin shortcuts. I think it will help you re-asign shortcuts. https://github.com/PeachScript/sketch-plugin-monster
