### ISSUE TITLE
plus not working?

### ISSUE THREAD

**Issue by seehadley** [rodi01/RenameIt#73]
I saw that there was a recent fix, but it is still not working for me. The + character is not pulling in the current name of the layer. I have Sketch 49.1 and the latest RenameIt (3.7.2).

Thanks!

**Comment by rodi01** [comment]
Sorry for that. I had to remove the plus because it was causing conflicts. If you use %* it should do the same thing.

**Comment by seehadley** [comment]
Ah, got it. Thanks for the workaround.
