### ISSUE TITLE
Plugin window not opening in sketch 49.3 (running rename-it 3.8.0)

### ISSUE THREAD

**Issue by spania85** [rodi01/RenameIt#75]
Hi guys, pretty much the title, on version 49.3 the plugin doesn't even load (I click on the plugin and the usually pop-up never opens), tried calling it from the plugins menu and from Runner, tried uninstalling and re-installing the plugin. Using version 3.8.0
On version 49.2 works fine though.
Thank you!

**Comment by rodi01** [comment]
I will take a look on that. Have you tried  restarting sketch?

**Comment by rodi01** [comment]
@spania85 is there any chance you could look at the log files for me? 
/Applications/Utilities/Console.app

it should be under report

![console](https://user-images.githubusercontent.com/52461/35641318-b606ea76-0674-11e8-9c6b-fc06cbf6034d.png)

**Comment by rodi01** [comment]
Update to the latest 3.8.1 and give it a try.

**Comment by vaernim** [comment]
Hello there,

I'm having the same loading issue as @spania85 (Sketch 49.3), even with the 3.8.1 version. 
Here's my log file.
[Plugin Output.log](https://github.com/rodi01/RenameIt/files/1954815/Plugin.Output.log)

**Comment by rodi01** [comment]
Please update to the latest version, I reverted back to an old version. I will try to fix this issue in the meantime.

**Comment by vaernim** [comment]
El Capitan (10.11.6). 
I've just updated the plugin and it works perfectly (layer, artboard and find & replace options).
Thank you!
