### ISSUE TITLE
Shortcut Control  + Command + R not working for Sketch 49.3

### ISSUE THREAD

**Issue by dwinurhadia** [rodi01/RenameIt#79]
Shortcut Control  + Command + R not working for Sketch 49.3

**Comment by dwinurhadia** [comment]
We used Mac Sierra 10.12.6

**Comment by rodi01** [comment]
@dwinurhadia Sorry for the long wait on this. The issue is that you probably have another plugin overwriting the shortcut. I use this plugin, https://github.com/PeachScript/sketch-plugin-monster, to manage the shortcuts. It will also tell you if there is any duplicates

**Comment by dwinurhadia** [comment]
Dear Sir,
Thank you for informations
