### ISSUE TITLE
Feature request: Rename layer to layer style name

### ISSUE THREAD

**Issue by jonmh85** [rodi01/RenameIt#82]
Would be good to be able to rename all layers with a layer style applied to the name of the layer style. This would be useful when handing designs to developers.

**Comment by richardsison** [comment]
I'd actually like the exact same thing but with Text Styles.

@rodi01 should I create a new Feature Request? Or is it similar enough?

**Comment by rodi01** [comment]
@richardsison I think it's similar enough, I will see what's involved to get this done.
What do you think it should happen if a selected layer doesn't have a text style? Should it be blank or not rename at all?

**Comment by richardsison** [comment]
@rodi01 Good one. If there isn't a text style, maybe it skips the renaming by default. It might be a good idea to have a checkbox to change to a user-defined name (i.e. Unnamed Text Style).

In a lot of cases I wouldn't want ALL text layers renamed, so having some control here is important. But if I'm trying to quickly isolate my styled from unstyled, that'd be helpful too. As long as I can make it by selection, or "all" (i.e. All = ideally by Page? Don't think I need by artboard, not sure if selecting artboard is the same as selecting a bunch of groups)

Question: Is there a way for you to know whether a text layer is an edited version of a text style? Example: When you've manually edited a text style and the asterisk appears next to the name (_Text Style_*)

**Comment by rodi01** [comment]
I think the safest way will be by selection. If the selection doesn't have a style, just skip it. 

In regards to edited text style, I really don't know. I need to dig into the text and layer styles, I've never looked at the API for that

**Comment by richardsison** [comment]
Hi there @rodi01, I swear this feature was introduced already… Has the latest version of RenameIt removed it? I don't do this often, but it's a really helpful tool to rename all text styles to their Layer Style name.

**Comment by richardsison** [comment]
I may have been mistaken. In the Automate Sketch plugin I found it: 

`Automate > Style > Rename Layer to Style Name`.

This would make a lot of sense in RenameIt though honestly! Hope it makes its way in there…

**Comment by rodi01** [comment]
I've added this feature on the latest beta, if anyone can help me test it will be greatly appreciated. 
You can download the beta here: https://github.com/rodi01/RenameIt/releases/download/v4.2.0/Rename-It.sketchplugin.zip

<img width="504" alt="Screen Shot 2019-05-17 at 3 53 23 PM" src="https://user-images.githubusercontent.com/52461/57960215-74300680-78bc-11e9-8009-dca8bdc5420a.png">
