### ISSUE TITLE
Crashes Sketch 51.1 after use

### ISSUE THREAD

**Issue by scarysnow** [rodi01/RenameIt#83]
Getting consistent crashes with Sketch 51.1 right after batch renaming a group of layers with the plugin. Seems to happen at random intervals. Have disabled other plugins, and issue still occurs.

**Comment by rodi01** [comment]
@scarysnow Could you send me the log? 
Open the console app under reports go to:
~/Library/Logs/com.bohemiancoding.sketch3
<img width="1350" alt="screen shot 2018-07-17 at 3 22 17 pm" src="https://user-images.githubusercontent.com/52461/42848674-44f28f4a-89d5-11e8-80bb-77968cd88535.png">

**Comment by rodi01** [comment]
Does it happen when the rename it window shows up or after you press the rename button?

**Comment by scarysnow** [comment]
I'm closing this. Haven't experienced the crash in a few days after heavy use and a fresh reinstall. Will follow up if the issue reoccurs. Greatly appreciate the plugin, it's a huge part of a particular workflow of mine.
