### ISSUE TITLE
Latest release not working

### ISSUE THREAD

**Issue by innatan** [rodi01/RenameIt#86]
Can't rename my layers with the latest RenameIt release :(

**Comment by filippaskotsis** [comment]
Second this. It was working great until the latest release.

**Comment by rodi01** [comment]
Sorry about that guys, I’m taking a look on this. 

You can download the previous version here https://github.com/rodi01/RenameIt/releases/download/v3.8.7/Rename-It.sketchplugin.zip 

Just don’t update to the lastest. I will let you guys know once it’s fixed.

**Comment by everydayslang** [comment]
Thanks for posting a link to the old one ✌️

**Comment by rodi01** [comment]
Could you take a look on the console for any error?
/Applications/Utilities/Console.app

it should be under report
![](https://user-images.githubusercontent.com/52461/35641318-b606ea76-0674-11e8-9c6b-fc06cbf6034d.png)

**Comment by everydayslang** [comment]
I’m not showing anything in there. 🤷‍♂️

**Comment by rodi01** [comment]
Can you guys try to update to 3.9.1? I just reverted it back, until I have more time to look into this. 

Sorry for messing up everyone's workflow 😥

**Comment by everydayslang** [comment]
I only see up to 3.9.0 on the releases tab.

**Comment by everydayslang** [comment]
Yup, Thanks. Just needed to restart. 😉

**Comment by rodi01** [comment]
I wonder if one of you guys can test a version for me, since I can't reproduce the issue. 

Here is the version: https://www.dropbox.com/s/dl/hryf4uygq6m765e/Rename-It-webview-update.sketchplugin.zip

Thanks in advance.

**Comment by innatan** [comment]
This works flawlessly!

**Comment by everydayslang** [comment]
Yup, looks good to me!

**Comment by filippaskotsis** [comment]
Works great now!

**Comment by rodi01** [comment]
@filippaskotsis @everydayslang I'm assuming you guys re talking about the test version that I posted above, right?

**Comment by filippaskotsis** [comment]
@rodi01 yes, no issue at all, either with the test version you posted or with the 3.9.2 update that was pushed earlier

**Comment by everydayslang** [comment]
Yeah 3.9.3

**Comment by rodi01** [comment]
Can you guys try out the lastest version, 3.9.4, when you have a chance?

Thanks

**Comment by toasty1435** [comment]
For some reason when using the asterisk I can’t get the rename to use the existing layer name, it just replaces the existing name with an asterisk. Anyone else have this issue?
