### ISSUE TITLE
Asterisk Issue

### ISSUE THREAD

**Issue by toasty1435** [rodi01/RenameIt#88]
On 51.2 for some reason when using the asterisk I can’t get the rename to use the existing layer name, it just replaces the existing name with an asterisk. Anyone else have this issue?

**Comment by rodi01** [comment]
I just tried and it's working for me. Are you using %*? It was changed a few versions back to %* instead of only *

**Comment by toasty1435** [comment]
Ah, that might be it, I'll try when I go home tonight. Just learning the program so total noob here :)

Thanks for the quick response!
