### ISSUE TITLE
Crashing when renaming a slice....

### ISSUE THREAD

**Issue by jeffdingwell** [rodi01/RenameIt#89]
I'm running Sketch V 51.2.

If I try to rename a slice using your plugin, Sketch immediately crashes. When I restart, all plugins have been disabled. 

Below is the sample file that causes my app to crash as well as a screen shot of the other plugins I'm running in case you know of a conflict:

![image](https://user-images.githubusercontent.com/2708782/43593453-c1a5bb3a-9645-11e8-81f6-b1058e2f1dfd.png)

[crash.zip](https://github.com/rodi01/RenameIt/files/2254040/crash.zip)

**Comment by rodi01** [comment]
Sorry about that, I'm looking into this.
In regards to disabling all the plugins, that's a new feature on Sketch were if there is a crash they re-start in "safe mode". You just have to re-open sketch again

**Comment by jeffdingwell** [comment]
All good. Love your plugin, thank you for making it!

Jeff Dingwell
H:   (514) 495-1431
M:  (514) 714-9555

**Comment by rodi01** [comment]
@jeffsingwell FIY, I editEd your comment to remove your phone number. GitHub includes the email signature when replying via email, I’ve done the same thing in the past. 😝

**Comment by jeffdingwell** [comment]
Wow, thanks! I don’t really ever use Git, I thought this was a private email back to you. ☺

 

Jeff
