### ISSUE TITLE
Stopped Working in Sketch 48.2

### ISSUE THREAD

**Issue by chsWeb** [rodi01/RenameIt#92]
**Sketch Version:** 48.2

**Rename It Version:** 3.9.6-2

**Problem:**
Selecting layers, and attempting to use the Find and Replace feature of Rename It results in no action being taken - the Rename It UI does not appear.

Nothing in the Rename It plugin is responsive, including Settings.

**Comment by rodi01** [comment]
The plugin version 3.8.7 is the last one that works on Sketch <51. Sketch was supposed to do it automatically. Here is the link https://github.com/rodi01/RenameIt/releases/download/v3.8.7/Rename-It.sketchplugin.zip

**Comment by chsWeb** [comment]
Thank you for the link, I was REALLY missing this plugin. Just saved me several hours in my old, rusty, Sketch 48 file :)
