### ISSUE TITLE
Lowercase alphabet sequence busted

### ISSUE THREAD

**Issue by jgaylor** [rodi01/RenameIt#93]
Lowercase alphabet sequence '%a' is renaming my layer to 'a' rather than using the layer name and turning it into lowercase. I'm on 51.3. I've reinstalled the latest plugin.

**Comment by jgaylor** [comment]
Nevermind i'm an idiot

**Comment by rodi01** [comment]
No worries, I’m happy you could figure it out. There is almost no documentation on this you are not the first one to get confused with it.
