### ISSUE TITLE
Alphabetical order is in reverse

### ISSUE THREAD

**Issue by HopHopBrand** [rodi01/RenameIt#97]
Layers are being renamed in reverse order
https://i.imgur.com/KoT0AAH.png

I'd like it to be in this order: ABCDEFGH not HGFEDCBA

**Comment by rodi01** [comment]
The order is actually right, Sketch reads layers from the bottom to the top of the Layer List. I think I need to add a way to reverse the order as an option.

**Comment by HopHopBrand** [comment]
@rodi01 That would be great! Im using https://github.com/bomberstudios/artboard-manager to keep the layer organized but it organizes it in this way.

Thanks!!!
