### ISSUE TITLE
Tab to switch fields in Find and Replace

### ISSUE THREAD

**Issue by chris-mrtn** [rodi01/RenameIt#98]
Currently it requires the mouse to select the first field, then again to select the replace field. Ideally the first field is already selected, and tab would switch to the replace field.

**Comment by rodi01** [comment]
Which version are you on? I can't reproduce it on Sketch 52.1

**Comment by chris-mrtn** [comment]
I'm on 52 (66869)

**Comment by rodi01** [comment]
I just tried on 52, still can't reproduce it. Which MacOS are you running? I'm tying to figure it out how to debug this.
